[package]
name = "vowpalwabbit"
version = "8.7.0"
authors = ["Jack Gerrits <jack@jackgerrits.com>"]
edition = "2018"
repository = "https://github.com/jackgerrits/vowpalwabbit-rs"
license = "MIT"
description = "Rust types, and CLI for VowpalWabbit"

[features]
native-bindings = ["vowpalwabbit-sys"]

[[bench]]
name = "benchmarks"
harness = false

[dependencies]
nom = "5.0.0"
byteorder = "1.3.2"
vowpalwabbit-sys = { version = "8.7.0", optional = true }
bencher = "0.1.5"